### ISSUE TITLE
workflow for experience details

### ISSUE THREAD

**Issue by Karthikannamareddy** [Karthikannamareddy/New-Project#7]
const companynamesData = [
{
id: 1,
name: "Infosys",
}
{
id :2,
name: "deliotte",
}

role_type = [
{
id: 1,
name: "frontend developer",
},
{
id: 2,
name: "backend developer",
}
]

tablename: ExperienceDetails,
attributes:
id: number,
user_id: number,
company_name_id: number,
role: string,
date_of_joining : Date ,
date_of_ending: Date,
profile_type: string,
notice_period: number,

id company_name_id, date_of_joining date_of_ending  role-type, user_id  profile_type notice_period
1,        2                              2006               2008                 1               1                full             1 month
2         1                              2008               2012                 2               1               part             15 days

**Comment by karthiktechally** [comment]
const companynamesData = [
{
id: 1,
name: "Infosys",
}
{
id :2,
name: "deliotte",
}

role_type = [
{
id: 1,
name: "frontend developer",
},
{
id: 2,
name: "backend developer",
}
]

tablename: ExperienceDetails,
attributes:
id: number,
user_id: number,
company_name_id: number,
role: string,
date_of_joining : Date ,
date_of_ending: Date,
profile_type: string,
notice_period: number,

id company_name_id, date_of_joining date_of_ending role-type, user_id profile_type notice_period
1, 2 2006 2008 1 1 full 1 month
2 1 2008 2012 2 1 part 15 days
route: ap1/v1/jobs

for creating a job
endpoint: api/v1/jobs
method: post
req body : {

id: 1,
user_id: 1,
company_name_id: xc1vg,
role: front end developer,
date_of_joining : 11-02-2006,
date_of_ending:28-04-2008,
profile_type: part, full ,
notice_period: 1 month.
}

response : {
message : "experience details created successfully",
data : {
id: 1,
user_id: 1,
company_name_id: xc1vg,
role: front end developer,
date_of_joining : 11-02-2006,
date_of_ending:28-04-2008,
profile_type: part, full ,
notice_period: 1 month.
}

}
